import datetime

# This file was automatically generated by module/config/config_updater.py.
# Don't modify it manually.


class GeneratedConfig:
    """
    Auto generated configuration
    """

    # Group `Scheduler`
    Scheduler_Enable = False
    Scheduler_NextRun = datetime.datetime(2020, 1, 1, 3, 0)
    Scheduler_Command = 'Plana'
    Scheduler_SuccessInterval = 60
    Scheduler_FailureInterval = 120
    Scheduler_ServerUpdate = '03:00'

    # Group `Emulator`
    Emulator_ServerName = 'disabled'

    # Group `Error`
    Error_SaveError = False
    Error_OnePushConfig = 'provider: null'

    # Group `Optimization`
    Optimization_WhenTaskQueueEmpty = 'stay_there'

    # Group `PlanaEmulator`
    PlanaEmulator_Serial = '127.0.0.1:16416'
    PlanaEmulator_PackageName = 'YoStarJP'  # YoStarJP
    PlanaEmulator_ScreenshotMethod = 'DroidCast_raw'  # auto, ADB, ADB_nc, uiautomator2, aScreenCap, aScreenCap_nc, DroidCast, DroidCast_raw, scrcpy
    PlanaEmulator_TouchMethod = 'minitouch'  # ADB, uiautomator2, minitouch, Hermit

    # Group `Storage`
    Storage_Storage = {}
