from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

GENERAL_GOTO_MAIN = Button(area={'jp': (1216, 5, 1253, 41)}, color={'jp': (179, 191, 212)}, button={'jp': (1216, 5, 1253, 41)}, file={'jp': 'C:/Users/mion/Desktop/ws/AzurLaneAutoScript/submodule/AlasPlana/assets/jp/ui/GENERAL_GOTO_MAIN.png'})
LOGIN_GOTO_SWITCHACCOUNT = Button(area={'jp': (36, 667, 252, 695)}, color={'jp': (81, 107, 135)}, button={'jp': (36, 667, 252, 695)}, file={'jp': 'C:/Users/mion/Desktop/ws/AzurLaneAutoScript/submodule/AlasPlana/assets/jp/ui/LOGIN_GOTO_SWITCHACCOUNT.png'})
MAIN_GOTO_CLUB = Button(area={'jp': (545, 636, 578, 655)}, color={'jp': (122, 212, 247)}, button={'jp': (545, 636, 578, 655)}, file={'jp': 'C:/Users/mion/Desktop/ws/AzurLaneAutoScript/submodule/AlasPlana/assets/jp/ui/MAIN_GOTO_CLUB.png'})
MAIN_GOTO_DUTIES = Button(area={'jp': (1141, 533, 1247, 571)}, color={'jp': (88, 191, 243)}, button={'jp': (1141, 533, 1247, 571)}, file={'jp': 'C:/Users/mion/Desktop/ws/AzurLaneAutoScript/submodule/AlasPlana/assets/jp/ui/MAIN_GOTO_DUTIES.png'})
MAIN_INFORM_BUTTON = Button(area={'jp': (538, 518, 742, 576)}, color={'jp': (112, 214, 248)}, button={'jp': (538, 518, 742, 576)}, file={'jp': 'C:/Users/mion/Desktop/ws/AzurLaneAutoScript/submodule/AlasPlana/assets/jp/ui/MAIN_INFORM_BUTTON.png'})
MAIN_INFORM_TITLE = Button(area={'jp': (607, 100, 672, 137)}, color={'jp': (169, 181, 193)}, button={'jp': (607, 100, 672, 137)}, file={'jp': 'C:/Users/mion/Desktop/ws/AzurLaneAutoScript/submodule/AlasPlana/assets/jp/ui/MAIN_INFORM_TITLE.png'})
MAIN_SCHALENEWS_BUTTON = Button(area={'jp': (1128, 87, 1156, 117)}, color={'jp': (100, 176, 250)}, button={'jp': (1128, 87, 1156, 117)}, file={'jp': 'C:/Users/mion/Desktop/ws/AzurLaneAutoScript/submodule/AlasPlana/assets/jp/ui/MAIN_SCHALENEWS_BUTTON.png'})
MAIN_SCHALENEWS_CHECKBOX_F = Button(area={'jp': (899, 631, 922, 655)}, color={'jp': (57, 82, 98)}, button={'jp': (899, 631, 922, 655)}, file={'jp': 'C:/Users/mion/Desktop/ws/AzurLaneAutoScript/submodule/AlasPlana/assets/jp/ui/MAIN_SCHALENEWS_CHECKBOX_F.png'})
MAIN_SCHALENEWS_CHECKBOX_T = Button(area={'jp': (897, 627, 920, 654)}, color={'jp': (68, 133, 159)}, button={'jp': (897, 627, 920, 654)}, file={'jp': 'C:/Users/mion/Desktop/ws/AzurLaneAutoScript/submodule/AlasPlana/assets/jp/ui/MAIN_SCHALENEWS_CHECKBOX_T.png'})
MAIN_SCHALENEWS_TITLE = Button(area={'jp': (121, 86, 324, 112)}, color={'jp': (146, 202, 254)}, button={'jp': (121, 86, 324, 112)}, file={'jp': 'C:/Users/mion/Desktop/ws/AzurLaneAutoScript/submodule/AlasPlana/assets/jp/ui/MAIN_SCHALENEWS_TITLE.png'})
RENKEI = Button(area={'jp': (559, 160, 716, 203)}, color={'jp': (199, 208, 217)}, button={'jp': (559, 160, 716, 203)}, file={'jp': 'C:/Users/mion/Desktop/ws/AzurLaneAutoScript/submodule/AlasPlana/assets/jp/ui/RENKEI.png'})
RENKEI_LOGIN = Button(area={'jp': (688, 462, 819, 505)}, color={'jp': (147, 232, 238)}, button={'jp': (688, 462, 819, 505)}, file={'jp': 'C:/Users/mion/Desktop/ws/AzurLaneAutoScript/submodule/AlasPlana/assets/jp/ui/RENKEI_LOGIN.png'})
SWITCHACCOUNT_GOTO_RENKEI = Button(area={'jp': (665, 482, 829, 520)}, color={'jp': (83, 193, 232)}, button={'jp': (665, 482, 829, 520)}, file={'jp': 'C:/Users/mion/Desktop/ws/AzurLaneAutoScript/submodule/AlasPlana/assets/jp/ui/SWITCHACCOUNT_GOTO_RENKEI.png'})
