from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CLUB_AWARD_BUTTON = Button(area={'jp': (548, 465, 732, 515)}, color={'jp': (110, 212, 247)}, button={'jp': (548, 465, 732, 515)}, file={'jp': 'C:/Users/mion/Desktop/ws/AzurLaneAutoScript/submodule/AlasPlana/assets/jp/club/CLUB_AWARD_BUTTON.png'})
CLUB_AWARD_TITLE = Button(area={'jp': (450, 140, 830, 178)}, color={'jp': (192, 202, 211)}, button={'jp': (450, 140, 830, 178)}, file={'jp': 'C:/Users/mion/Desktop/ws/AzurLaneAutoScript/submodule/AlasPlana/assets/jp/club/CLUB_AWARD_TITLE.png'})
