# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Plana ====================

Plana:
  menu: 'list'
  page: 'setting'
  tasks:
    Plana:
      - Emulator
      - Error
      - Optimization

Tools:
  menu: 'list'
  page: 'tool'
  tasks:
    PlanaCapTool:
      - CapTool