# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Plana ====================

Plana:
  menu: 'list'
  page: 'setting'
  tasks:
    Plana:
      - PlanaEmulator
      - Emulator
      - Error
      - Optimization